hostel/auth.py
from flask import Blueprint,render_template,request,flash,redirect,url_for,send_from_directory
from .models import User,hostellite,mess,message,info,infow,fee
from werkzeug.security import generate_password_hash,check_password_hash
from . import db
from flask_login import login_user , login_required , logout_user , current_user
from . import hostellite_db
from . import mess_db
from . import message_db
from . import info_db
from . import infow_db
from . import fee_db

auth = Blueprint('auth',__name__)

@auth.route('/login',methods=['GET','POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        hostel = request.form.get('hostel')

        user = User.query.filter_by(username=username).first()
        hostel_exists = User.query.filter_by(hostel=hostel).first()
        if user:
            if hostel_exists:
                if check_password_hash(user.password,password):
                    return render_template('warden_dashboard.html',username=username,hostel=hostel)
                else:
                    flash('Incorrect Password Entered',category='error')
                    return render_template('warden_login.html')
            else:
                 flash('Hostel name not found correct for given username',category='error')
                 return render_template('warden_login.html')       
        else:
            flash("Username doesn\'t exists. Please signup to get your hostel access to our site",category='error')    
            return render_template('warden_login.html')

    return render_template('warden_login.html')


@auth.route('/logout')
def logout():
    return "logout"

@auth.route('/signup',methods=['GET','POST'])
def signup():
    if(request.method == 'POST'):
        username = request.form.get('username')
        password = request.form.get('password')
        hostel = request.form.get('hostel')

        user = User.query.filter_by(username=username).first()
        hostel_h = User.query.filter_by(hostel=hostel).first()

        if user:
            flash('Username already exists',category='error')
            return render_template('warden_register.html')
        if len(username) < 1:
            flash("Please enter a valid username.",category='error')
        elif len(password) < 7:
            flash("Please enter a password having length more than 7",category='error')
        else:
            new_user = User(username=username,password=generate_password_hash(password ,method='sha256'),hostel=hostel)
            db.session.add(new_user)
            db.session.commit()
            redirect(url_for('views.home'))
            flash('Account created. Now please redirect to login page to access your account ',category='success')

    return render_template("warden_register.html")

@auth.route('/add_info',methods=['GET','POST'])
def add_info():
    if request.method == 'POST':
        new_name = request.form.get('new_name')
        new_floor = request.form.get('new_floor')
        new_room = request.form.get('new_room')
        new_hostel = request.form.get('hostel_name')
        new_entry = hostellite(username=new_name,hostel=new_hostel,room=new_room,floor=new_floor)
        to_check = hostellite.query.filter_by(username=new_name,hostel=new_hostel,room=new_room,floor=new_floor).first()
        already_full = hostellite.query.filter_by(hostel=new_hostel,room=new_room,floor=new_floor).first()
        if(not(to_check) or not(already_full)):
            hostellite_db.session.add(new_entry)
            hostellite_db.session.commit()
            data = hostellite.query.order_by(hostellite.username).all()
            flash("Database created",category='success')
            return render_template('add_hostellite.html', datas=data)
        else:
            flash("The given room has already been occupied by other hostellites",category='error')
            return render_template('add_hostellite.html')

    else:
        data = hostellite.query.order_by(hostellite.username).all()
        return render_template('add_hostellite.html',datas = data)

@auth.route('/add_mess',methods=['GET','POST'])
def add_mess():
    if(request.method == 'POST'):
        food = request.form.get('food')
        tye = request.form.get('type')
        day = request.form.get('day')

        new_entry = mess(food=food,type = tye,day = day)
        order = mess.query.order_by(mess.day).all()
        try:
            mess_db.session.add(new_entry)
            mess_db.session.commit()
            return render_template('add_mess.html',orders = order)
        except:
            return render_template('add_mess.html')
    else:
        return render_template('add_mess.html',orders = order)

@auth.route('/hostellite_login',methods=['GET','POST'])
def hostellite_login():
    if request.method == 'POST':
        username_h = request.form.get('username')
        hostel_h = request.form.get('hostel')
        user_h = hostellite.query.filter_by(username=username_h).first()
        hostel_exists_h = hostellite.query.filter_by(hostel=hostel_h).first()
        if hostel_exists_h:
            if user_h:               
                order = mess.query.order_by(mess.day).all() 
                print(username_h,'logged in !!')  
                return render_template('dashboard_hostellite.html',hostel = hostel_h,username=username_h,orders= order)
            else:
                flash("Username does\'nt exists please contact your hostel authoraties to create your account",category='error')
                return render_template('login.html')
        else:
            flash("Your hostel name doesnt exists on our database",category='error')
            return render_template('login.html')
    return render_template('login.html')

@auth.route('/send_message/<username>/<hostel>',methods=['GET','POST'])
def send_message(username,hostel):
    if request.method == 'POST':
        name = request.form.get('username')
        subject = request.form.get('Subject')
        query = request.form.get('Query')
        to_add = message(username = name,subject=subject,info=query)
        try:
            message_db.session.add(to_add)
            message_db.session.commit()
            flash("Message sent",category='success')
            redirect(url_for('roomands',username=username,hostel=hostel))
        except:
            return render_template('RoomandServices.html',username=username,hostel=hostel)
    else:
        return render_template('RoomandServices.html',username=username,hostel=hostel)


@auth.route('/get_message')
def read_messages():
    if request.method == 'GET':
        info = message.query.order_by(message.username).all()
        return render_template('message_for_warden.html',infos=info)

@auth.route('/search_hostellites/<username>/<hostel>', methods=['GET','POST'])
def search(username,hostel):
    if request.method == 'POST':
        name = request.form.get('name')
        hoste = request.form.get('hostel')
        details = hostellite.query.filter_by(username=name, hostel=hoste).first()
        add_details = info.query.filter_by(name=name).order_by(info.id.desc()).first()
        if(details):
            return render_template('search.html', info=details, more_info=add_details,username=username,hostel=hostel)
        else:
            return render_template('search.html',info=None, more_info=None,username=username,hostel=hostel,notfound = True)
    else:
        return render_template('search.html', info=None,more_info = None,username=username,hostel=hostel)


@auth.route('/show_profile/<username>/<hostel>', methods=['GET', 'POST'])
def show_profile(username,hostel):
    if request.method == 'GET':
        user_detail = hostellite.query.filter_by(username=username).first()
        data = info.query.filter_by(name=username).order_by(info.id.desc()).first()
        return render_template('profile_user.html',  user=user_detail,datas=data,username=username,hostel=hostel)
    else:
        clg = request.form.get('college')
        stream = request.form.get('stream')
        name = request.form.get('name')
        phone = request.form.get('phone')
        infos = info(name=name,college=clg,stream=stream,phone=phone)
        try:
            info_db.session.add(infos)
            info_db.session.commit()
            user_detail = hostellite.query.filter_by(username=username).first()
            data = info.query.filter_by(name=username).order_by(info.id.desc()).first()
            return render_template('profile_user.html',  user=user_detail,datas = data,username=username,hostel=hostel)
        except:
            flash("Couldn't excess database",category='error')
            return render_template('profile_user.html',username=username,hostel=hostel)

@auth.route('/warden_profile/<username>/<hostel>', methods=['GET', 'POST'])
def warden_profile(username, hostel):
    if request.method == 'GET':
        user_detail = User.query.filter_by(username=username).first()
        data = infow.query.filter_by(name=username).order_by(infow.id.desc()).first()
        return render_template('warden_profile.html', user=user_detail, datas=data,username=username,hostel=hostel)
    elif request.method == 'POST':
        phone = request.form.get('phone')
        add = request.form.get('add')
        name = request.form.get('name')
        infos = infow(name=name, add=add, phone=phone)
        try:
            infow_db.session.add(infos)
            infow_db.session.commit()
            user_detail = User.query.filter_by(username=username).first()
            data = infow.query.filter_by(name=username).order_by(infow.id.desc()).first()
            return render_template('warden_profile.html', user=user_detail, datas=data,username=username,hostel=hostel)
        except:
            flash("Couldn't access database", category='error')
            return render_template('warden_profile.html.html', username=username, hostel=hostel)

hostel/views.py
#we will store standard route of our website
from flask import Blueprint,render_template,request,redirect,url_for
from flask_sqlalchemy import SQLAlchemy
from flask_login import login_required,current_user
from .models import User,hostellite,message,fee
from . import mess_db
from . import message_db
from . import fee_db
from .models import mess
views = Blueprint('views',__name__)

@views.route('/')
def home():
    return render_template('profiles.html')

@views.route('/hostelliteLogin')
def hostellitelogin():
    return render_template('login.html')

@views.route('/wardenLogin')
def wardenlogin():
    return render_template('warden_login.html')

@views.route('/wardenRegister')
def wardenRegister():
    return render_template('warden_register.html')

@views.route('/add_hostellite')
def add_hostellite():
    return render_template('add_hostellite.html')

@views.route('/add_mess')
def add_mess():
    return render_template('add_mess.html')


@views.route('/warden_dahsboard')
def warden_dashboard():
    return render_template('warden_dashboard.html')

@views.route('/roomsandservices/<username>/<hostel>')
def roomands(username,hostel):
    order = mess.query.order_by(mess.day).all()
    return render_template('RoomandServices.html',username=username,orders= order,hostel=hostel)


@views.route('/rent/<username>/<hostel>', methods=['GET', 'POST'])
def rent(username, hostel):
    from content import app
    import os
    if request.method == 'GET':
        order = mess.query.order_by(mess.day).all() 
        return render_template('hhpaymentform.html', username=username, orders=order, hostel=hostel)
    elif request.method == 'POST':
        order = mess.query.order_by(mess.day).all() 
        name = request.form.get('name')
        hoste = request.form.get('hostel')
        phone = request.form.get('phone')
        file = request.files['file'] 
        room = request.form.get('room')
        file.save(os.path.join(app.config['UPLOAD_FOLDER'], file.filename))
        details = fee(name=name, hostel=hoste, phone=phone, file=file.filename, room=room) 
        try:
            fee_db.session.add(details)
            fee_db.session.commit()
            return render_template('hhpaymentform.html', username=username, orders=order, hostel=hostel)
        except:
            return render_template('hhpayment.html', username=username, orders=order, hostel=hostel)


@views.route('/messageforwardem', methods=['GET','POST'])
def message_for_warden():
    if request.method == 'GET':
        info = message.query.order_by(message.username).all()
        return render_template('message_for_warden.html',infos=info)
    elif request.method == 'POST':
        message_id = request.form.get('message_id')
        message_to_delete = message.query.filter_by(id=message_id).first()
        try:
            message_db.session.delete(message_to_delete)
            message_db.session.commit()
            return redirect(url_for('auth.read_messages'))
        except:
            return render_template('message_for_warden.html')
    
@views.route('/search_hostellite/<username>/<hostel>')
def search(username,hostel):
    order = mess.query.order_by(mess.day).all() 
    return render_template('search.html',info=None,more_info = None,username=username,orders= order,hostel=hostel,nothing=True)

@views.route('/hostellite_dashboard/<username>/<hostel>',methods=['GET'])
def hostellite_dashboard(username,hostel):
    order = mess.query.order_by(mess.day).all() 
    return render_template('dashboard_hostellite.html',username=username,orders= order,hostel=hostel)

hostel/templates/RoomandServices.html
{% extends 'dashboard_hostellite.html' %}
<!DOCTYPE html>
<html lang="en">
  {% block head %}
<head>
  {{super() }}
  <link rel="stylesheet" href="{{ url_for('static', filename='RoomandServices.css') }}">
  <style>
    form{
      width: 2000px;
    }
  </style>
</head>
{% endblock %}
<body>
  {% block name %} {% endblock %}
  {% block user %}{% endblock %}
      {% block content %}
     <form method="post" action="{{url_for('auth.send_message',username=username,hostel=hostel)}}"> 
    <div class="send_message">
    <h1>Queries & Messages</h1>
    <p>Name: <input type="text" name="username" placeholder="Enter Name" required></p>
    <p>Subject :  <input type="text" name="Subject" placeholder="Enter Subject" required></p>
    <p><textarea name="Query" id="" cols="80" rows="20" placeholder="Enter your Query Here" required></textarea></p>
    <p><input type="submit" value="Submit" onclick="myFunc(event)"></p>
    </form>
    {% endblock %}
    <script>
      function myFunc(event) {
        alert("Message sent");
      }
    </script>
</div>
</body>
</html>

hostel/templates/dashboard_hostellite.html
<!-- @format -->

<!DOCTYPE html>
<html lang="en">
  {% block head %}
  <head>
    <meta charset="UTF-8" />
    {% block title %}
    <title>Hostellite Dashboard</title>
    {% endblock %}
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='dashboard_hostellite.css')}}"
    />

    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=Phudu:wght@600&display=swap"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />
    <style>
      a,
      a[id="mode"] {
        cursor: pointer;
        font-family: "Phudu", cursive;
        text-align: left;
        justify-content: left;
      }

      b {
        font-family: Phudu, cursive;
      }
      tbody {
        color: teal;
        font-family: Phudu, cursive;
      }
      /* customize the profile button */
      #tocen {
        background-color: teal;
        color: white;
        font-size: 16px;
        font-family: Phudu, cursive;
        cursor: pointer;
        border-radius: 15px;
        border: 3px solid teal;
        text-align: center;
        align-items: center;
        padding: 5px;
        width: 100px;
        margin-top: 15px;
        transition: 0.1s;
      }
      /* hover setting */
      #tocen:hover {
        background-color: turquoise;
        color: teal;
        border: 3px solid teal;
      }

      div.profile {
        text-align: center;
        align-items: center;
        display: flex;
        justify-content: center;
      }
      h1 {
        text-align: center;
      }

      h4,
      div.col {
        font-family: Phudu, cursive;
        font-size: 20px;
        /* move it to the right */
        text-align: center;
      }

      /* align the table properly */
      table,
      th,
      td {
        font-family: Phudu, cursive;
        border-collapse: collapse;
        padding: 10px;
        text-align: center;
      }
    </style>
  </head>
  {% endblock %}
  <body>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category,message in messages %} {% if category=='error'
    %}
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
      {{ message }}
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
      {{ message }}
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <div class="container">
      <nav>
        <ul>
          <li>
            <a href="#" class="logo">
              <img
                src="https://imgs.search.brave.com/J0Qf01tOs4e_SLcUAve9f_WOxYYDoTHflPALjXxgrMg/rs:fit:474:225:1/g:ce/aHR0cHM6Ly90c2Uz/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC50/ZzZUWkpzamZVR0o3/dmlTc2JYQ0JRSGFI/YSZwaWQ9QXBp"
              />
              <span class="nav-item">{{username}}</span>
            </a>
          </li>
          {% block dash %}

          <li>
            <a
              href="{{url_for('views.hostellite_dashboard',username=username,hostel=hostel)}}"
            >
              <i class="fas fa-menorah"></i>
              <span class="nav-item"><b>Dashboard</b></span>
            </a>
          </li>

          {% endblock %}

          <li>
            {% block link %}
            <a
              href="{{url_for('views.roomands',username=username,hostel=hostel)}}"
            >
              {% endblock %}
              <i class="fas fa-comment"></i>
              <span class="nav-item"><b>Queries</b></span>
            </a>
          </li>

          {% block link1 %}
          <a href="{{url_for('views.rent',username=username,hostel=hostel)}}">
            <i class="fas fa-database"></i>
            <span class="nav-item"><b>Rent</b></span>
          </a>

          {% endblock %} {% block link2 %}
          <li>
            <a
              href="{{url_for('views.search',username=username,hostel=hostel)}}"
            >
              <i class="fas fa-search"></i>
              <span class="nav-item"><b>Find fellow hostellites</b></span>
            </a>
          </li>

          {% endblock %}
          <li>
            <a href="{{url_for('views.home')}}" class="logout">
              <i class="fas fa-sign-out-alt"></i>
              <span class="nav-item">Log out</span>
            </a>
          </li>
        </ul>
      </nav>
      {% block user %}
      <section class="main">
        <div class="main-top">
          {% block name %}
          <h1 align="center">Dashboard</h1>
          {% endblock %}
        </div>
        <div class="users">
          <div class="card">
            <div class="col">
              <img
                src="https://imgs.search.brave.com/J0Qf01tOs4e_SLcUAve9f_WOxYYDoTHflPALjXxgrMg/rs:fit:474:225:1/g:ce/aHR0cHM6Ly90c2Uz/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC50/ZzZUWkpzamZVR0o3/dmlTc2JYQ0JRSGFI/YSZwaWQ9QXBp"
              />
              <h4>{{username}}</h4>
            </div>

            <div class="col">
              Hostel : {{hostel}}
              <br />
            </div>
            {% block profile %}
            <div class="profile">
              <a
                href="{{url_for('auth.show_profile',username=username,hostel=hostel)}}"
                id="tocen"
              >
                Profile
              </a>
            </div>
          </div>
        </div>
        {% endblock %} {% endblock %} {% block content %}
        <section class="attendance">
          <div class="attendance-list">
            <h1>Menu</h1>
            <table class="table">
              <thead>
                <tr>
                  <th>Food</th>
                  <th>type</th>
                  <th>Day</th>
                  <!-- <th>Details</th> -->
                </tr>
              </thead>
              <tbody>
                {% for order in orders %}
                <tr>
                  {% if order.food %}
                  <td>{{order.food}}</td>
                  <td>{{order.type}}</td>
                  <td>{{order.day}}</td>
                  <!-- <td><button>View</button></td> -->
                  {% endif %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </section>
      </section>
    </div>
    {% endblock %}
  </body>
</html>

hostel/templates/search.html
<!-- @format -->

<!DOCTYPE html>
<html lang="en">
  <head>
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=Phudu:wght@600&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='search.css')}}"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Search other hostellites</title>
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='dashboard_hostellite.css')}}"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=Phudu:wght@600&display=swap"
      rel="stylesheet"
    />

    <style>
      input[id="submit"]{
        cursor: pointer;
      }
      td,th{
        width: 100px;
      }
     h1 {
        font-family: "Phudu", cursive;
        font-size: 55px;
        color: rgb(0, 81, 255);
      }

      body {
        background-color: lightcyan;
        display: flex;
        align-items: center;
        justify-self: center;
        flex-direction: column;
        font-family: "Phudu", cursive;
      }
      table {
        position: relative;
        text-align: center;
        align-items: center;
        justify-content: center;
        background: white;
        margin-top: 55px;
        /* fix the table position */
        margin-left: 100px;
        margin-right: 100px;
        border-radius: 15px;

      }

      label{
        font-size: 20px;
        font-family: "Phudu", cursive;
        color: black;
      }

      form {
        font-size: 20px;
        margin-left: 100px;
      }

      caption {
        font-size: 30px;
        color: black;
        font-family: "Phudu", cursive;
        margin-bottom: 20px;
        border-top: 3px solid rgb(0, 81, 255);
        margin-top: 10px;
      }

      td {
        text-align: center;
        border: 3px solid rgb(0, 81, 255);
        position: relative;
        max-width: 100%;
        padding: 40px 80px;
      }
      th {
        position: relative;
        text-align: center;
        border: 3px solid rgb(0, 81, 255);
        max-width: 100%;
        font-size: 19px;
      }
      input {
        border: 1px solid rgb(0, 81, 255);
        border-radius: 15px;
        margin-top: 15px;
        padding: 10px;
        font-family: "Phudu", cursive;
        cursor: beaming;
        transition: 0.09s;
        font-size: 15px;
        text-align: center;
      }

      #add {
        background-color: rgb(0, 81, 255);
        color: white;
        border: 1px solid rgb(0, 81, 255);
        border-radius: 15px;
        margin-top: 20px;
        padding: 15px;
        font-family: "Phudu", cursive;
        cursor: pointer;
        transition: border 0.09s;
        margin-left: 155px;
        font-size: 15px;
        width: 100px;
        margin-bottom: -15px;
        
      }

      #add:hover {
        border: 3px solid rgb(0, 81, 255);
        color: rgb(0, 81, 255);
        background-color: white;
      }

      table {
        margin: 0 auto;
        width: 50%;
      }
      
    </style>
  </head>

  <body>
    <div class="container">
      <nav>
        <ul>
          <li>
            <a href="#" class="logo">
              <img
                src="https://imgs.search.brave.com/J0Qf01tOs4e_SLcUAve9f_WOxYYDoTHflPALjXxgrMg/rs:fit:474:225:1/g:ce/aHR0cHM6Ly90c2Uz/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC50/ZzZUWkpzamZVR0o3/dmlTc2JYQ0JRSGFI/YSZwaWQ9QXBp"
              />
              <span class="nav-item">{{username}}</span>
            </a>
          </li>
          <li>
            <a href="{{url_for('views.hostellite_dashboard',username=username,hostel=hostel)}}">
              <i class="fas fa-menorah"></i>
              <span class="nav-item"><b>Dashboard</b></span>
            </a>
          </li>
          <li>
            <a href="{{url_for('views.roomands',username=username,hostel=hostel)}}">
              <i class="fas fa-comment"></i>
              <span class="nav-item"><b>Queries</b></span>
            </a>
          </li>
          <li>
            <a href="{{url_for('views.rent',username=username,hostel=hostel)}}">
              <i class="fas fa-database"></i>
              <span class="nav-item"><b>Rent</b></span>
            </a>
          </li>
          <li>
            <a href="{{url_for('views.search',username=username,hostel=hostel)}}">
              <i class="fas fa-search"></i>
              <span class="nav-item"><b>Find fellow hostellites</b></span>
            </a>
          </li>
          <li>
            <a href="{{url_for('views.home')}}" class="logout">
              <i class="fas fa-sign-out-alt"></i>
              <span class="nav-item">Log out</span>
            </a>
          </li>
        </ul>
      </nav>
      
<section class="attendance">
  <div class="attendance-list">
        <h1 align="center">Search Hostellite</h1>
        <div class="to_cen">
        <form action="{{url_for('auth.search',username=username,hostel=hostel)}}" method="post">
          <label for="new_name">Name: </label> <br>
          <input type="text" id="name" name="name" /> <br />
          <label for="hostel_name">Hostel Name:</label>  <br>
          <input type="text" id="hostel" name="hostel" />  <br>
          <input type="submit" name="submit" id="submit">
        </div>
        </form>
        <table>
          {% if nothing %}
          <div class="nothing"><input type="text" hidden></div>
          {% elif notfound or info.username == "" %}
          <div class="not_found"> No search results found of given user in our database </div>
          {% else %}
          <caption>
            Details
          </caption>
          {% if info.username %}
          <tr>
            <th>Name</th>
            <th>Hostel</th>
            <th>Floor</th>
            <th>ROOM</th>
            <th>College</th>
            <th>Stream</th>
            <th>Phone Number</th>
          </tr>
          <tr>
            <td>{{info.username}}</td>
            <td>{{info.hostel}}</td>
            <td>{{info.floor}}</td>
            <td>{{info.room}}</td>
            {% endif %}
            {% if more_info.college %}
            <td>{{more_info.college}}</td>
            <td>{{more_info.stream}}</td>
            <td>{{more_info.phone}}</td>
            {% endif %}
          </tr>
          {% endif %}
        </table>  
  </div>
</section>
</section>
</div>
  </body>
</html>

hostel/templates/warden_dashboard.html
{% extends 'dashboard_hostellite.html' %}
{% block head %}
<head>
{{super()}}
<style>
  .ql {
    margin-top: 40px;
    font-family: "Phudu", cursive;
    text-align: center;
    font-size: 70px;
    color: rgb(0, 81, 255);
  }
  .links {
    font-size: 20px;
    align-items: center;
    display: flex;
    justify-content: center;
    flex-direction: column;
  }
  .links > a {
    text-decoration: none;
    text-align: center;
    color: blue;
    padding: 10px;
    border: 2px solid rgb(0, 81, 255);
    border-radius: 10px;
    margin: 10px;
    transition: border 0.1s linear;
    font-family: "Phudu", cursive;
  }
  hr{
    margin-top: 50px;
    border: 2px solid blue;
  }

  .links > a:hover {
    font-family: "Phudu", cursive;
    color: teal;
    border: 5px teal solid;
  }
</style>
</head>
{% endblock %}
{% block dash %}
<li>
  <a href="#">
    <i class="fas fa-menorah"></i>
    <span class="nav-item"><b>Dashboard</b></span>
  </a>
</li>
{% endblock %}
{% block link %}
    <a href="{{url_for('views.message_for_warden')}}">
{% endblock %}
{% block link1 %} {% endblock %} 
{% block link2 %} 
<li>
  <a href="{{url_for('auth.fee_status',hostel=hostel)}}">
    <i class="fas fa-search"></i>
    <span class="nav-item"><b>Check Fee status</b></span>
  </a>
</li>
{% endblock %}
{% block user %} 
{{super()}}
{% endblock %}
{% block profile %}
<div class="profile">
  <a
href="{{url_for('auth.warden_profile',username=username,hostel=hostel)}}" 
id="tocen" >
Profile
</a>
</div>
{% endblock %}
{% block content %}
<hr />
<div class="ql">Quick Links <br /></div>
<div class="links">
  <a href="{{url_for('views.add_hostellite')}}" id="link1">Add Hostellite</a
  >
  <a href="{{url_for('views.add_mess')}}" id="link2">ADD/UPDATE mess menu</a>
</div>
{% endblock %}

hostel/templates/warden_login.html
{% extends 'login.html' %}
{% block title %}<title>Warden Login</title>{% endblock %}
{%block content %}
{%block form %}<form method="post" action="{{url_for('auth.login')}}"> {% endblock %}
<div class="signup_link">
    Hostel Name not found? <br>
    <a href = "{{url_for('views.wardenRegister')}}">
       <small>Sign-up and get access</small>
    </a>
</div>
{{ super() }}
{% endblock %}

hostel/templates/warden_register.html
{% extends 'login.html' %}

{% block title %} <title>Warden Register</title> {% endblock %}
{% block content %}
{%block form %}<form method="post" action="{{url_for('auth.signup')}}"> {% endblock %}
    <input type="submit" value="Register" name="submitform">
    Already have an account?
    <a href="{{url_for('views.wardenlogin')}}"><small>Sign in</small></a>
{% endblock %}